name: Test

on:
  workflow_dispatch:

jobs:
  ask:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model: [ 'gemma3', 'tinyllama']
    steps:
      - name: Run Ollama prompt
        id: ollama
        uses: evanallen13/Ollama-Action@main
        with:
          model: ${{ matrix.model }}
          prompt: 'What is the capital of France?'
          cache: 'true'

      - name: Print response
        run: echo "${{ steps.ollama.outputs.response }}"
